### PR TITLE
Feature/Greyscale and Monochrome colour modes

### PR DESCRIPTION
**Pull request by HTimms**
I made an issue for this last week, where the product I'm working on needs a colour picker that will be able to limit the range of colours, since some of the printers we use can't handle full colour, or are monochrome label printers. 

I had a go at implementing colour modes, with 'color' being the default mode, which is just what the colour picker already does, so it shouldn't have an effect on existing implementations. 

But, I'm only a junior, so I might have missed something or done it in an unclean way, so feedback is certainly welcomed!

### CODE REVIEW

**Comment by sconix** [comment]
Thanks for the PR. I will go through this during this week and comment / merge depending if there is any issues left.

**Comment by sconix** [comment]
Just to update that I have not forgotten this, but did not have time to check it before my holiday. So this will be merged after one more week when my holiday is over.

**Comment by HTimms** [comment]
Has there been any update on the reviewing of this recently? 

Cheers

**Comment by sconix** [comment]
I got back from my holiday on Tuesday and been super busy couple days. I should be able to check and release this on Sunday.

**Comment by HTimms** [comment]
The intention was that Monochrome would only allow one colour at all, meaning there can only be one preset, whereas Limited would allow only presets, but you can have as many presets as you like. 

The scenario envisioned was that we'd have a printer that can only print in black, so we'd set the colour picker to 'Monochrome' and set to black, so the user can only select black as a colour. 

However, I was then informed that we also have these special dual band printers that can print in only black and red, so I added the 'Limited' mode so that it would limit the user's choices to black and red. 

I hope this explains things a little!

**Comment by HTimms** [comment]
Though, having had a few minutes to think about it, it might be better just to remove the 'Monochrome' mode entirely and replace it with 'Limited', since the latter can quite easily serve the same purpose if you only have one preset. 

Thoughts?

**Comment by HTimms** [comment]
The original purpose was to make it so Monochrome only allows one colour preset and nothing else, whereas Limited only allows you to choose from presets, but you can have as many presets as you like. 

Though, having had a few minutes to think about it, it might be better just to remove the 'Monochrome' mode entirely and replace it with 'Limited', since the latter can quite easily serve the same purpose if you only have one preset. 

Thoughts?

**Comment by sconix** [comment]
Ok that explains it a bit. So limited would only allow alpha (if enabled) and selection of the preset colors?

Yes the monochrome at the moment at least is not very useful so if you want it to be included it should be "fixed". Since I would expect that to only allow selecting of the color level (like the greyscale but with one color i.e. hence not forced to grey).

So I can either remove the monochrome option or wait until you fix it if you want it to be included.

**Comment by sconix** [comment]
So if I understand correctly. The grayscale only allows selecting a grayscale color (and this works afaik as it should). The monochrome really should allow only selecting a value for single color  (atm this does not allow changing the value) and limited would only allow alpha if enabled and selecting a preset color (this also works already).

**Comment by HTimms** [comment]
I'd be okay with 'Monochrome' being removed, as 'Limited' serves our needs just as well.

**Comment by HTimms** [comment]
> So if I understand correctly. The grayscale only allows selecting a grayscale color (and this works afaik as it should). The monochrome really should allow only selecting a tone for single color (atm this does not allow changing the tone) and limited would only allow alpha if enabled and selecting a preset color (this also works already).
> 
> So if thats correct then everything else works except the monochrome which basically is just the same as limited atm. So if its supposed to be what it says I think it should allow changing the tone of the color + alpha if enabled.


As you said, Grayscale does what it should. However, the difference between Monochrome and Limited should be that in Monochrome, you can only have one colour at one specific tone, since monochrome printers can only print in one colour, at one intensity. This is why in Monochrome Mode, you cannot change the colour you've picked. If the colour you've picked is "#f00", that's all it's going to be and it can't be anything else. 

Limited is basically going "You cannot pick any other colour than the ones you have pre-set", so you could have maybe five different presets, but you can't pick any colours outside of those presets (with optional alpha). 

'Monochrome' could be removed and replaced with 'Limited', since you could quite easily just have the colour picker set to 'Limited' with only one preset and achieve the same effects as 'Monochrome'. 

I hope this elaborates a little on what the intention was.

**Comment by sconix** [comment]
@HTimms I just merged this to master with small changes and improvements. Could you check that its still fills your needs and it looks ok to you.

The changes I made was that I removed the custom presets handling (I think presets needs to be always in the hands of the developer no matter what color mode) and renamed the 'limited' to 'presets'. I also removed the monochrome. Let me know if you think I missed something.

**Comment by HTimms** [comment]
It looks okay to me! Feel free to release!

**Comment by HTimms** [comment]
Okay, I've had some time to properly test it beyond looking at the code. It looks like it's working fine to me, but I forgot to add the new color modes to the examples, but that probably isn't a priority. 

Other than that, it looks to be working fine.

**Pull request merged**
