### PR TITLE
Use "display" property instead of "visibility" property.

### PR DESCRIPTION
**Pull request by srikanthb935**
To avoid an unnecessary white space at the bottom of the file, we can use "display" property instead of "visibility" property.

### CODE REVIEW

**Comment by srikanthb935** [comment]
Stackblitz: https://stackblitz.com/edit/angular-zqnd3x

When we try to open the color picker it is adding extra space at the bottom(able to see in the above Stackblitz example, where it is adding extra space at the bottom so we will be able to see scroll)

**Comment by sconix** [comment]
Thanks, I will have to test this well since I have a feeling that using display can cause problems for the dialog size calculations in some situations. Have you tried with the different dialog modes and height values to see if there is any problems with this change?

**Comment by srikanthb935** [comment]
I have tested with different sizes and it is working fine.

**Comment by sconix** [comment]
Ok, I will merge this for next release which should be soon.

**Comment by sconix** [comment]
@srikanthb935 This change is now causing a bug in positioning the dialog as I suspected. So I will be reverting this change. In your case I would say the main issue is not having enough space for the dialog when opened so I do not see the extra space when dialog is closed as that big of an issue. Since if its just the dialog causing a scroll and you do not need it otherwise you can just add overflow visible to the container. Or you can use the useRootViewContainer feature that places the dialog to the root container. 

I will add a class stating the open state to the dialog so you can easily implement the using of display instead of visibility if you want, but I can not make it the default since it causes issues in some situations like placing the dialog on top where the height of the dialog is needed and is not available when using display none.

**Comment by srikanthb935** [comment]
@sconix Okay fine and thank you for suggesting other possibilities.

**Pull request merged**
