### PR TITLE
Add support for cmyk format #23

### PR DESCRIPTION
**Pull request by bubba5656**
[cpOutputFormat]="'cmyk'"
colors emmited will still be RGB

to obtain CMYKA color observe
cpCmykColor directive
if inputformat is CMYK value else you will get empty string

### CODE REVIEW

**Comment by sconix** [comment]
I now checked this PR and I think the usage of the cpOutputFormat is confusing. Why is that even needed if the output format wont be cmyk? Could there just be a new configuration parameter cpEnableCmyk with cpCmykChange event? This way the usage would be more logical.

**Comment by bubba5656** [comment]
The reason I chose cpOutputFormat as CMYK is this will allow the color picker to come up in CMYK color space. I simply extended the functionality that was already present. For existing users of the color-picker, CMYK is just another option. The selected color will have to be as RGB.  If we output CMYK color, then color picker will not be able to display the selected CMYK color because browsers don't support CMYK.  
If the user wants to see the actual CMYK value then they need to listen to cpCmykChange this will give them.

In your proposal how will cpEnableCmyk work?  How can we set default color space as CMYK?

**Comment by sconix** [comment]
I am just suggesting that cpEnableCmyk=true would be equal to what cpOutputFormat='cmyk' does now. This way the change event can emit with the selected cpOutputFormat like it is meant to so its not too confusing to document. Since at the moment it is that other options will change the format of output except cmyk.

**Comment by sconix** [comment]
This will be in the 8.0.0 release with the change I mentioned that instead of using cpOutputFormat one needs to set cpCmykEnabled to true.

**Pull request closed without merging**
