### PR TITLE
Allow to force Alpha channel on Output

### PR DESCRIPTION
**Pull request by maxkorz**

### CODE REVIEW

**Comment by sconix** [comment]
Thanks, I am not sure if there is going to be confusion with the different alpha options (i.e. this and cpAlphaChannel). But I think this is more clear and the cpAlphaChannel could be deprecated (i.e. when using cpForceAlpha is true and output format is hex then the output would be hex8). Maybe I do that when merging this so we can leave out the cpAlphaChannel in future versions.

**Comment by maxkorz** [comment]
Yes, you're right, `cpForceAlpha=true` in conjunction with `cpAlphaChannel='disabled'` is confusing. Didn't think of that. I did this for rgb format.

Will you accept my pull request or you want me to make some changes?

**Comment by maxkorz** [comment]
Maybe `cpAlphaChannel` can be renamed to `cpShowAlphaSlider` (boolean)? Then it will not interfere with `cpForceAlpha`

**Comment by maxkorz** [comment]
or rename my `cpForceAlpha` to `cpForceRgbAlpha` and leave `cpAlphaChannel` as is

**Comment by sconix** [comment]
I think the PR is good as it is, but I will make small change when I merge this in couple days. Not sure yet which road I will take, but I will simplify the alpha configuration a bit.

**Comment by sconix** [comment]
I changed this so that I removed the cpForceAlpha input and changed the cpAlphaChannel to have the possibility to be set to 'always'. That forces the alpha channel in the output no matter what output format is used. This will be in the 4.2.0 release which will make later today. Thanks for the PR!

**Pull request merged**
