### PR TITLE
Add option to configure event propagation mode

### PR DESCRIPTION
**Pull request by antkiewicz**
Fix issue with mousedown and mouseup events not firing when color picker component is injected into dynamically created DOM container element with external JS library. Setting a mouse event registrations with useCapture flag to true solves this issue.

### CODE REVIEW

**Comment by sconix** [comment]
Are you sure that adding useCapture wont cause problems in some use cases? I am just thinking that should this have some toggle or preferably could it be detected somehow that is the useCapture needed.

**Comment by antkiewicz** [comment]
@sconix Good question. I have spent some more time trying to figure why only certain events (mousedown and mouseup) would not get triggered. It turns out the issue is NOT with color picker. In my case I needed to use a consistent color picker across the whole application, even in WYSIWG editor's popup. In the end it was the WYSIWYG stopping event propagation from color picker that was injected into it.

I can do a work around for this on my implementation side. However if you would accept this as possible feature, then I can amend my commit into a configuration option. Adding new option of "cpUseCapture" with default being false?

**Comment by sconix** [comment]
I though so that something might be stopping the events. I have to think a bit if this would be a good feature or not. Since normally there should not be no need to capture the events, but I guess it would not hurt to have an option for it so maybe I merge this for next update.

**Comment by sconix** [comment]
I looked some other libs and none of them provide option for controlling the capture so I think I will for now close this, but if you or somebody strongly thinks that this is a needed feature I can merge this.

**Pull request closed without merging**
