### PR TITLE
auto position

### PR DESCRIPTION
**Pull request by DebuggerAK**
auto position + new positions (left-top, left-bottom, right-top, right-bottom) + top, left, right, bottom removed

### CODE REVIEW

**Comment by DebuggerAK** [comment]
How is the situation?

Best regards!

**Comment by sconix** [comment]
I am on a holiday atm, will merge and release next week!

**Comment by DebuggerAK** [comment]
How is the current situation?

**Comment by sconix** [comment]
I had to continue my holiday, will merge asap when I am back in the beginning of next week.

**Comment by DebuggerAK** [comment]
Thank you very much! Works fine! I use 'auto' only.

**Comment by sconix** [comment]
I only added back support for the old position naming and some aliases for the positions for easier usage. Thanks for the PR!

**Pull request merged**
