### PR TITLE
Add ability to emit color change only after mouseup

### PR DESCRIPTION
**Pull request by Gubernskiy**

### CODE REVIEW

**Comment by sconix** [comment]
Thanks. I am just thinking about the implementation, would it be better if this would work the same way as cpOkButton? What I mean that there basically would not be no need for code changes or they would be very minimal and more importantly there would not be yet another input option.

So what I am proposing is that what if the mouseup would send the colorPickerSelect event just like the ok button does. Then one could just ignore the color change event (I mean not use the change output) if not interested of the changes and would just listen to colorPickerSelect event which would be send on mouseup. So what do you think? 

If you think that would be ok, I can easily add such a small change so no need to re-factor this PR.

**Comment by Gubernskiy** [comment]
I don't think it will work for me. In my situation i need no only emit new color but also dont't change the initial color before mouseup event. that's why i add one more input. But maybe there is better solution.

**Comment by sconix** [comment]
What do you mean by not change the initial color? Initial color of the color picker? Maybe you could add your html code so I can see what inputs/outputs you use.

I am pretty sure there is bit simpler way to do this I just need to fully understand your use case. And it would be good to simplify the code in general so that it can handle all different situations for emitting the color change, but without adding configuration options. This would seem like a good case for another interface cleanup / generalization like with the alpha channel change while a go.

**Comment by Gubernskiy** [comment]
`<input [(colorPicker)]="color16"
                   [style.background]="color16"
                   [cpAlphaChannel]="'always'"
                   [cpOutputFormat]="'rgba'"/>`

When i open color picker and start choosing the new color. the background will change the same time because they use the same variable but i need to change it only after mouseup. I understand that i can do something like this when it will emit color on mouseup.

`<input [(colorPicker)]="color16"
                   [style.background]="color17"
                   [cpAlphaChannel]="'always'"
                   [cpOutputFormat]="'rgba'"
                   (colorPickerSelect)="color17=$event"/>`

But i don't think it is better.

**Comment by sconix** [comment]
With my proposed fix it would be like this:
<input [colorPicker]="color16" [style.background]="color16" [cpAlphaChannel]="'always'" [cpOutputFormat]="'rgba'" (colorPickerSelect)="color16=$event"/>

When you use [()] it means that you are already binding the input value to the change event. The ng-model works that way. But when you leave out the () then you can handle the setting of your color value from the events for example.

Now when I think of this I think we can't use the select event since then you would need to check if its mouseup or ok button event, but what we can and imho should do is to add colorPickerDragStart and colorPickerDragEnd events sending. So the code would be the same except instead colorPickerSelect you would tap into colorPickerDragEnd event.

**Comment by Gubernskiy** [comment]
Thanks. I didn't think about [()]. Everything became simple.  For me will be fine just to emit colorPickerSelect. I will not check what event it was. So can you add this emit? And i will not re-factor this PR. Am i right and it will be emit on slider and input changes too? or i should use (cpSliderChange)  and (cpInputChange) for this.

**Comment by sconix** [comment]
I will add the cpDragStart/End events for all the color "sliders". Naturally those wont emit when input is changed, but for that you can use the existing cpInputChange. So I will close this PR now and will release new 4.3.0 version with the drag events tomorrow or at the latest day after tomorrow.

**Comment by Gubernskiy** [comment]
Ok. Thanks you

**Pull request closed without merging**
