### PR TITLE
Upgraded to Angular 13 and enabled Ivy.

### PR DESCRIPTION
**Pull request by magnusbakken**
Upgraded to Angular 13 and enabled Ivy.

There doesn't seem to be a version of @angular-devkit/build-ng-packagr that supports ng-packagr 13 yet, so it's necessary to ignore some NPM dependency warnings when installing.

### CODE REVIEW

**Comment by magnusbakken** [comment]
Installation warnings should be gone now.

**Comment by eran10** [comment]
any update here? can this be merged ?

**Comment by shayh** [comment]
@zefdevel any chance you can merge this?

**Comment by sconix** [comment]
I will be making new release soon and will include this among couple other PR's

**Pull request merged**
